import { ValueObject } from '../../../../shared/value-object.base';

export enum CurrencyEnum {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  CAD = 'CAD',
  AUD = 'AUD',
  JPY = 'JPY',
  CHF = 'CHF',
  CNY = 'CNY',
  SEK = 'SEK',
  NOK = 'NOK',
  DKK = 'DKK',
  PLN = 'PLN',
  CZK = 'CZK',
  HUF = 'HUF',
  RON = 'RON',
  BGN = 'BGN',
  HRK = 'HRK',
  RSD = 'RSD',
  MKD = 'MKD',
  BAM = 'BAM',
  ALL = 'ALL',
  MDL = 'MDL',
  UAH = 'UAH',
  BYN = 'BYN',
  RUB = 'RUB',
  TRY = 'TRY',
  ILS = 'ILS',
  AED = 'AED',
  SAR = 'SAR',
  QAR = 'QAR',
  KWD = 'KWD',
  BHD = 'BHD',
  OMR = 'OMR',
  JOD = 'JOD',
  LBP = 'LBP',
  EGP = 'EGP',
  MAD = 'MAD',
  TND = 'TND',
  DZD = 'DZD',
  LYD = 'LYD',
  SDG = 'SDG',
  ETB = 'ETB',
  KES = 'KES',
  UGX = 'UGX',
  TZS = 'TZS',
  RWF = 'RWF',
  BIF = 'BIF',
  DJF = 'DJF',
  SOS = 'SOS',
  ERN = 'ERN',
  SHP = 'SHP',
  ZAR = 'ZAR',
  BWP = 'BWP',
  SZL = 'SZL',
  LSL = 'LSL',
  NAD = 'NAD',
  MWK = 'MWK',
  ZMW = 'ZMW',
  ZWL = 'ZWL',
  AOA = 'AOA',
  CDF = 'CDF',
  XAF = 'XAF',
  XOF = 'XOF',
  XPF = 'XPF',
  MGA = 'MGA',
  MUR = 'MUR',
  SCR = 'SCR',
  KMF = 'KMF',
  MVR = 'MVR',
  INR = 'INR',
  PKR = 'PKR',
  BDT = 'BDT',
  LKR = 'LKR',
  NPR = 'NPR',
  BTN = 'BTN',
  THB = 'THB',
  LAK = 'LAK',
  KHR = 'KHR',
  VND = 'VND',
  MYR = 'MYR',
  SGD = 'SGD',
  BND = 'BND',
  IDR = 'IDR',
  PHP = 'PHP',
  MMK = 'MMK',
  KRW = 'KRW',
  KPW = 'KPW',
  MNT = 'MNT',
  KZT = 'KZT',
  UZS = 'UZS',
  TJS = 'TJS',
  TMT = 'TMT',
  AFN = 'AFN',
  IRR = 'IRR',
  IQD = 'IQD',
  SYP = 'SYP',
  YER = 'YER',
  GEL = 'GEL',
  AMD = 'AMD',
  AZN = 'AZN',
  MXN = 'MXN',
  GTQ = 'GTQ',
  BZD = 'BZD',
  SVC = 'SVC',
  HNL = 'HNL',
  NIO = 'NIO',
  CRC = 'CRC',
  PAB = 'PAB',
  COP = 'COP',
  VES = 'VES',
  GYD = 'GYD',
  SRD = 'SRD',
  TTD = 'TTD',
  BBD = 'BBD',
  JMD = 'JMD',
  HTG = 'HTG',
  DOP = 'DOP',
  CUP = 'CUP',
  ARS = 'ARS',
  UYU = 'UYU',
  PYG = 'PYG',
  BOB = 'BOB',
  PEN = 'PEN',
  CLP = 'CLP',
  BRL = 'BRL',
  FKP = 'FKP',
  GIP = 'GIP',
  ISK = 'ISK',
  FJD = 'FJD',
  PGK = 'PGK',
  SBD = 'SBD',
  VUV = 'VUV',
  NC = 'NC',
  WST = 'WST',
  TOP = 'TOP',
  TVD = 'TVD',
  KID = 'KID',
  NUF = 'NUF',
  NZD = 'NZD',
}

export class CurrencyVO extends ValueObject<CurrencyEnum> {
  constructor(value: CurrencyEnum) {
    super(value);
    this.validate();
  }

  private validate(): void {
    if (!Object.values(CurrencyEnum).includes(this.value)) {
      throw new Error(`Invalid currency: ${this.value}`);
    }
  }

  static fromString(currency: string): CurrencyVO {
    const normalizedCurrency = currency.toUpperCase() as CurrencyEnum;
    return new CurrencyVO(normalizedCurrency);
  }

  get symbol(): string {
    const symbols: Record<CurrencyEnum, string> = {
      [CurrencyEnum.USD]: '$',
      [CurrencyEnum.EUR]: '€',
      [CurrencyEnum.GBP]: '£',
      [CurrencyEnum.CAD]: 'C$',
      [CurrencyEnum.AUD]: 'A$',
      [CurrencyEnum.JPY]: '¥',
      [CurrencyEnum.CHF]: 'CHF',
      [CurrencyEnum.CNY]: '¥',
      [CurrencyEnum.SEK]: 'kr',
      [CurrencyEnum.NOK]: 'kr',
      [CurrencyEnum.DKK]: 'kr',
      [CurrencyEnum.PLN]: 'zł',
      [CurrencyEnum.CZK]: 'Kč',
      [CurrencyEnum.HUF]: 'Ft',
      [CurrencyEnum.RON]: 'lei',
      [CurrencyEnum.BGN]: 'лв',
      [CurrencyEnum.HRK]: 'kn',
      [CurrencyEnum.RSD]: 'дин',
      [CurrencyEnum.MKD]: 'ден',
      [CurrencyEnum.BAM]: 'КМ',
      [CurrencyEnum.ALL]: 'L',
      [CurrencyEnum.MDL]: 'L',
      [CurrencyEnum.UAH]: '₴',
      [CurrencyEnum.BYN]: 'Br',
      [CurrencyEnum.RUB]: '₽',
      [CurrencyEnum.TRY]: '₺',
      [CurrencyEnum.ILS]: '₪',
      [CurrencyEnum.AED]: 'د.إ',
      [CurrencyEnum.SAR]: '﷼',
      [CurrencyEnum.QAR]: '﷼',
      [CurrencyEnum.KWD]: 'د.ك',
      [CurrencyEnum.BHD]: '.د.ب',
      [CurrencyEnum.OMR]: '﷼',
      [CurrencyEnum.JOD]: 'د.ا',
      [CurrencyEnum.LBP]: '£',
      [CurrencyEnum.EGP]: 'ج.م',
      [CurrencyEnum.MAD]: 'د.م.',
      [CurrencyEnum.TND]: 'د.ت',
      [CurrencyEnum.DZD]: 'د.ج',
      [CurrencyEnum.LYD]: 'د.ل',
      [CurrencyEnum.SDG]: 'ج.س.',
      [CurrencyEnum.ETB]: 'Br',
      [CurrencyEnum.KES]: 'KSh',
      [CurrencyEnum.UGX]: 'USh',
      [CurrencyEnum.TZS]: 'TSh',
      [CurrencyEnum.RWF]: 'RF',
      [CurrencyEnum.BIF]: 'FBu',
      [CurrencyEnum.DJF]: 'Fdj',
      [CurrencyEnum.SOS]: 'S',
      [CurrencyEnum.ERN]: 'Nfk',
      [CurrencyEnum.SHP]: '£',
      [CurrencyEnum.ZAR]: 'R',
      [CurrencyEnum.BWP]: 'P',
      [CurrencyEnum.SZL]: 'L',
      [CurrencyEnum.LSL]: 'L',
      [CurrencyEnum.NAD]: 'N$',
      [CurrencyEnum.MWK]: 'MK',
      [CurrencyEnum.ZMW]: 'ZK',
      [CurrencyEnum.ZWL]: 'Z$',
      [CurrencyEnum.AOA]: 'Kz',
      [CurrencyEnum.CDF]: 'FC',
      [CurrencyEnum.XAF]: 'FCFA',
      [CurrencyEnum.XOF]: 'CFA',
      [CurrencyEnum.XPF]: '₣',
      [CurrencyEnum.MGA]: 'Ar',
      [CurrencyEnum.MUR]: '₨',
      [CurrencyEnum.SCR]: '₨',
      [CurrencyEnum.KMF]: 'CF',
      [CurrencyEnum.MVR]: 'Rf',
      [CurrencyEnum.INR]: '₹',
      [CurrencyEnum.PKR]: '₨',
      [CurrencyEnum.BDT]: '৳',
      [CurrencyEnum.LKR]: '₨',
      [CurrencyEnum.NPR]: '₨',
      [CurrencyEnum.BTN]: 'Nu.',
      [CurrencyEnum.THB]: '฿',
      [CurrencyEnum.LAK]: '₭',
      [CurrencyEnum.KHR]: '៛',
      [CurrencyEnum.VND]: '₫',
      [CurrencyEnum.MYR]: 'RM',
      [CurrencyEnum.SGD]: 'S$',
      [CurrencyEnum.BND]: 'B$',
      [CurrencyEnum.IDR]: 'Rp',
      [CurrencyEnum.PHP]: '₱',
      [CurrencyEnum.MMK]: 'K',
      [CurrencyEnum.KRW]: '₩',
      [CurrencyEnum.KPW]: '₩',
      [CurrencyEnum.MNT]: '₮',
      [CurrencyEnum.KZT]: '₸',
      [CurrencyEnum.UZS]: 'лв',
      [CurrencyEnum.TJS]: 'SM',
      [CurrencyEnum.TMT]: 'T',
      [CurrencyEnum.AFN]: '؋',
      [CurrencyEnum.IRR]: '﷼',
      [CurrencyEnum.IQD]: 'ع.د',
      [CurrencyEnum.SYP]: '£',
      [CurrencyEnum.YER]: '﷼',
      [CurrencyEnum.GEL]: '₾',
      [CurrencyEnum.AMD]: '֏',
      [CurrencyEnum.AZN]: '₼',
      [CurrencyEnum.MXN]: '$',
      [CurrencyEnum.GTQ]: 'Q',
      [CurrencyEnum.BZD]: 'BZ$',
      [CurrencyEnum.SVC]: '$',
      [CurrencyEnum.HNL]: 'L',
      [CurrencyEnum.NIO]: 'C$',
      [CurrencyEnum.CRC]: '₡',
      [CurrencyEnum.PAB]: 'B/.',
      [CurrencyEnum.COP]: '$',
      [CurrencyEnum.VES]: 'Bs',
      [CurrencyEnum.GYD]: 'G$',
      [CurrencyEnum.SRD]: '$',
      [CurrencyEnum.TTD]: 'TT$',
      [CurrencyEnum.BBD]: 'Bds$',
      [CurrencyEnum.JMD]: 'J$',
      [CurrencyEnum.HTG]: 'G',
      [CurrencyEnum.DOP]: 'RD$',
      [CurrencyEnum.CUP]: '₱',
      [CurrencyEnum.ARS]: '$',
      [CurrencyEnum.UYU]: '$U',
      [CurrencyEnum.PYG]: 'Gs',
      [CurrencyEnum.BOB]: '$b',
      [CurrencyEnum.PEN]: 'S/.',
      [CurrencyEnum.CLP]: '$',
      [CurrencyEnum.BRL]: 'R$',
      [CurrencyEnum.FKP]: '£',
      [CurrencyEnum.GIP]: '£',
      [CurrencyEnum.ISK]: 'kr',
      [CurrencyEnum.FJD]: 'FJ$',
      [CurrencyEnum.PGK]: 'K',
      [CurrencyEnum.SBD]: 'SI$',
      [CurrencyEnum.VUV]: 'VT',
      [CurrencyEnum.NC]: '₣',
      [CurrencyEnum.WST]: 'WS$',
      [CurrencyEnum.TOP]: 'T$',
      [CurrencyEnum.TVD]: '$',
      [CurrencyEnum.KID]: '$',
      [CurrencyEnum.NUF]: '$',
      [CurrencyEnum.NZD]: 'NZ$',
    };

    return symbols[this.value] || this.value;
  }

  get decimalPlaces(): number {
    // Most currencies use 2 decimal places, but some use 0 or 3
    const zeroDecimalCurrencies = [
      CurrencyEnum.JPY,
      CurrencyEnum.KPW,
      CurrencyEnum.VND,
      CurrencyEnum.XAF,
      CurrencyEnum.XOF,
      CurrencyEnum.XPF,
    ];

    const threeDecimalCurrencies = [
      CurrencyEnum.BHD,
      CurrencyEnum.JOD,
      CurrencyEnum.KWD,
      CurrencyEnum.OMR,
      CurrencyEnum.TND,
    ];

    if (zeroDecimalCurrencies.includes(this.value)) return 0;
    if (threeDecimalCurrencies.includes(this.value)) return 3;
    return 2;
  }

  get isZeroDecimal(): boolean {
    return this.decimalPlaces === 0;
  }
}
