import { z } from 'zod';

export enum CurrencyCodes {
  AFN = 'AFN',
  ALL = 'ALL',
  EUR = 'EUR',
  DZD = 'DZD',
  AOA = 'AOA',
  XCD = 'XCD',
  SAR = 'SAR',
  ARS = 'ARS',
  AMD = 'AMD',
  AWG = 'AWG',
  AUD = 'AUD',
  AZN = 'AZN',
  BSD = 'BSD',
  BDT = 'BDT',
  BBD = 'BBD',
  BHD = 'BHD',
  BZD = 'BZD',
  XOF = 'XOF',
  BMD = 'BMD',
  BYR = 'BYR',
  MMK = 'MMK',
  BOB = 'BOB',
  BOV = 'BOV',
  USD = 'USD',
  BAM = 'BAM',
  BWP = 'BWP',
  BRL = 'BRL',
  BND = 'BND',
  BGN = 'BGN',
  BIF = 'BIF',
  BTN = 'BTN',
  INR = 'INR',
  CVE = 'CVE',
  KHR = 'KHR',
  XAF = 'XAF',
  CAD = 'CAD',
  CLF = 'CLF',
  CLP = 'CLP',
  CNY = 'CNY',
  COP = 'COP',
  COU = 'COU',
  KMF = 'KMF',
  CDF = 'CDF',
  CRC = 'CRC',
  HRK = 'HRK',
  CUC = 'CUC',
  CUP = 'CUP',
  ANG = 'ANG',
  DKK = 'DKK',
  EGP = 'EGP',
  SVC = 'SVC',
  AED = 'AED',
  ERN = 'ERN',
  ETB = 'ETB',
  FJD = 'FJD',
  PHP = 'PHP',
  XDR = 'XDR',
  GMD = 'GMD',
  GEL = 'GEL',
  GHS = 'GHS',
  GIP = 'GIP',
  GNF = 'GNF',
  GTQ = 'GTQ',
  GYD = 'GYD',
  HTG = 'HTG',
  HNL = 'HNL',
  HKD = 'HKD',
  HUF = 'HUF',
  IDR = 'IDR',
  IQD = 'IQD',
  NOK = 'NOK',
  ISK = 'ISK',
  KYD = 'KYD',
  FKP = 'FKP',
  SBD = 'SBD',
  ILS = 'ILS',
  JMD = 'JMD',
  JPY = 'JPY',
  GBP = 'GBP',
  JOD = 'JOD',
  KZT = 'KZT',
  KES = 'KES',
  KGS = 'KGS',
  KWD = 'KWD',
  LSL = 'LSL',
  ZAR = 'ZAR',
  LRD = 'LRD',
  LYD = 'LYD',
  CHF = 'CHF',
  LBP = 'LBP',
  MOP = 'MOP',
  MKD = 'MKD',
  MGA = 'MGA',
  MYR = 'MYR',
  MWK = 'MWK',
  MVR = 'MVR',
  MAD = 'MAD',
  MUR = 'MUR',
  MRO = 'MRO',
  MNT = 'MNT',
  MZN = 'MZN',
  MXN = 'MXN',
  MXV = 'MXV',
  NAD = 'NAD',
  NPR = 'NPR',
  NIO = 'NIO',
  NGN = 'NGN',
  NZD = 'NZD',
  XPF = 'XPF',
  OMR = 'OMR',
  XUA = 'XUA',
  PKR = 'PKR',
  PAB = 'PAB',
  PGK = 'PGK',
  PYG = 'PYG',
  PEN = 'PEN',
  PLN = 'PLN',
  QAR = 'QAR',
  LAK = 'LAK',
  VEF = 'VEF',
  CZK = 'CZK',
  KRW = 'KRW',
  MDL = 'MDL',
  KPW = 'KPW',
  DOP = 'DOP',
  IRR = 'IRR',
  TZS = 'TZS',
  SYP = 'SYP',
  RWF = 'RWF',
  RON = 'RON',
  RUB = 'RUB',
  WST = 'WST',
  STD = 'STD',
  RSD = 'RSD',
  SCR = 'SCR',
  SLL = 'SLL',
  SGD = 'SGD',
  XSU = 'XSU',
  SOS = 'SOS',
  LKR = 'LKR',
  SZL = 'SZL',
  SDG = 'SDG',
  SSP = 'SSP',
  SEK = 'SEK',
  CHE = 'CHE',
  CHW = 'CHW',
  SRD = 'SRD',
  THB = 'THB',
  TWD = 'TWD',
  TJS = 'TJS',
  TOP = 'TOP',
  TTD = 'TTD',
  TMT = 'TMT',
  TRY = 'TRY',
  TND = 'TND',
  UGX = 'UGX',
  UAH = 'UAH',
  UYI = 'UYI',
  UYU = 'UYU',
  UZS = 'UZS',
  VUV = 'VUV',
  VND = 'VND',
  YER = 'YER',
  DJF = 'DJF',
  ZMW = 'ZMW',
  ZWL = 'ZWL',
}

export const currencySchema = z.nativeEnum(CurrencyCodes).nullish();

export class Currency {
  private readonly value: CurrencyCodes;

  private constructor(value: CurrencyCodes) {
    this.value = value;
  }

  public static create(type: string): Currency {
    const validatedType = currencySchema.parse(type);
    return new Currency(validatedType);
  }

  public getValue(): CurrencyCodes {
    return this.value;
  }

  public equals(currency: Currency): boolean {
    return this.value === currency.value;
  }
}
